# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run Tests
        env:
          pytest_verbosity: 1
        run: uv run bolt run-unit-tests

      - name: Code Coverate Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: output/**/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "75 85"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Build Documentation
        run: uv run sphinx-build -M html docs/source docs/build

      - name: Build Package
        run: uv build
